#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Twilight.Dao
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AppLog")]
	public partial class TwilightDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public TwilightDataContext() : 
				base(global::Twilight.Dao.Properties.Settings.Default.AppLogConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TwilightDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TwilightDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TwilightDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TwilightDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Account_CheckFunctionPermission")]
		public int Account_CheckFunctionPermission([global::System.Data.Linq.Mapping.ParameterAttribute(Name="LoginID", DbType="VarChar(20)")] string loginID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FunctionID", DbType="Int")] System.Nullable<int> functionID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccessLevel", DbType="Int")] System.Nullable<int> accessLevel)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), loginID, functionID, accessLevel);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.state_LogTrendByLevel")]
		public ISingleResult<state_LogTrendByLevelResult> state_LogTrendByLevel([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UseDBTime", DbType="Bit")] System.Nullable<bool> useDBTime, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PastHrs", DbType="TinyInt")] System.Nullable<byte> pastHrs, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BUID", DbType="SmallInt")] System.Nullable<short> bUID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BaseDateTime", DbType="DateTime")] ref System.Nullable<System.DateTime> baseDateTime)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), useDBTime, pastHrs, bUID, baseDateTime);
			baseDateTime = ((System.Nullable<System.DateTime>)(result.GetParameterValue(3)));
			return ((ISingleResult<state_LogTrendByLevelResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Account_CheckLoginIDExist")]
		public int Account_CheckLoginIDExist([global::System.Data.Linq.Mapping.ParameterAttribute(Name="LoginID", DbType="VarChar(20)")] string loginID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), loginID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Account_Delete")]
		public int Account_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="SmallInt")] System.Nullable<short> userID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Account_GetALLUser")]
		public ISingleResult<Account_GetALLUserResult> Account_GetALLUser()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Account_GetALLUserResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Account_Insert")]
		public int Account_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="LoginID", DbType="VarChar(20)")] string loginID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="VarChar(50)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SessionID", DbType="VarChar(50)")] string sessionID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LoginAttempt", DbType="TinyInt")] System.Nullable<byte> loginAttempt, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PositionID", DbType="Int")] System.Nullable<int> positionID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BUID", DbType="SmallInt")] System.Nullable<short> bUID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="VarChar(50)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EMail", DbType="VarChar(128)")] string eMail, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Remark", DbType="VarChar(256)")] string remark, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="Int")] System.Nullable<int> status, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserType", DbType="Int")] System.Nullable<int> userType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Picture", DbType="Image")] System.Data.Linq.Binary picture, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PictureType", DbType="VarChar(5)")] string pictureType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CreatedBy", DbType="SmallInt")] System.Nullable<short> createdBy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="SmallInt")] ref System.Nullable<short> userID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), loginID, password, sessionID, loginAttempt, positionID, bUID, userName, eMail, remark, status, userType, picture, pictureType, createdBy, userID);
			userID = ((System.Nullable<short>)(result.GetParameterValue(14)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Account_PasswordInsert")]
		public int Account_PasswordInsert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="SmallInt")] System.Nullable<short> userID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="VarChar(50)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SessionID", DbType="VarChar(50)")] string sessionID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LoginAttempt", DbType="TinyInt")] System.Nullable<byte> loginAttempt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID, password, sessionID, loginAttempt);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Account_PasswordUpdate")]
		public int Account_PasswordUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="SmallInt")] System.Nullable<short> userID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="VarChar(50)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SessionID", DbType="VarChar(50)")] string sessionID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LoginAttempt", DbType="TinyInt")] System.Nullable<byte> loginAttempt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID, password, sessionID, loginAttempt);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Account_Search")]
		public ISingleResult<Account_SearchResult> Account_Search([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Keyword", DbType="VarChar(1000)")] string keyword, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="Int")] System.Nullable<int> status, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BUID", DbType="SmallInt")] System.Nullable<short> bUID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pageNum, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pageSize, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VirtualRowsCount", DbType="Int")] ref System.Nullable<int> virtualRowsCount)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), keyword, status, bUID, pageNum, pageSize, virtualRowsCount);
			virtualRowsCount = ((System.Nullable<int>)(result.GetParameterValue(5)));
			return ((ISingleResult<Account_SearchResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Account_SearchByUserID")]
		public ISingleResult<Account_SearchByUserIDResult> Account_SearchByUserID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="SmallInt")] System.Nullable<short> userID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID);
			return ((ISingleResult<Account_SearchByUserIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Account_Update")]
		public int Account_Update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="SmallInt")] System.Nullable<short> userID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="VarChar(50)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SessionID", DbType="VarChar(50)")] string sessionID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LoginAttempt", DbType="TinyInt")] System.Nullable<byte> loginAttempt, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PositionID", DbType="Int")] System.Nullable<int> positionID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BUID", DbType="SmallInt")] System.Nullable<short> bUID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="VarChar(50)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EMail", DbType="VarChar(128)")] string eMail, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Remark", DbType="VarChar(256)")] string remark, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="TinyInt")] System.Nullable<byte> status, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserType", DbType="TinyInt")] System.Nullable<byte> userType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Picture", DbType="Image")] System.Data.Linq.Binary picture, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PictureType", DbType="VarChar(5)")] string pictureType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UpdatedBy", DbType="SmallInt")] System.Nullable<short> updatedBy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID, password, sessionID, loginAttempt, positionID, bUID, userName, eMail, remark, status, userType, picture, pictureType, updatedBy);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Account_UserPositionInsert")]
		public int Account_UserPositionInsert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="SmallInt")] System.Nullable<short> userID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PositionID", DbType="Int")] System.Nullable<int> positionID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CreatedBy", DbType="Int")] System.Nullable<int> createdBy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID, positionID, createdBy);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Account_UserPositionUpdate")]
		public int Account_UserPositionUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="SmallInt")] System.Nullable<short> userID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PositionID", DbType="Int")] System.Nullable<int> positionID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UpdatedBy", DbType="Int")] System.Nullable<int> updatedBy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID, positionID, updatedBy);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Account_ValidateUser")]
		public int Account_ValidateUser([global::System.Data.Linq.Mapping.ParameterAttribute(Name="LoginID", DbType="VarChar(20)")] string loginID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="VarChar(50)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="Int")] ref System.Nullable<int> userID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BUID", DbType="SmallInt")] ref System.Nullable<short> bUID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PositionID", DbType="Int")] ref System.Nullable<int> positionID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), loginID, password, userID, bUID, positionID);
			userID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			bUID = ((System.Nullable<short>)(result.GetParameterValue(3)));
			positionID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BU_Delete")]
		public int BU_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BUID", DbType="SmallInt")] System.Nullable<short> bUID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), bUID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BU_Insert")]
		public int BU_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BUName", DbType="VarChar(50)")] string bUName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), bUName);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BU_Update")]
		public int BU_Update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BUName", DbType="VarChar(50)")] string bUName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BUID", DbType="SmallInt")] System.Nullable<short> bUID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), bUName, bUID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllBU")]
		public ISingleResult<GetAllBUResult> GetAllBU()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetAllBUResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllPosition")]
		public ISingleResult<GetAllPositionResult> GetAllPosition()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetAllPositionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetBUByID")]
		public ISingleResult<GetBUByIDResult> GetBUByID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BUID", DbType="SmallInt")] System.Nullable<short> bUID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), bUID);
			return ((ISingleResult<GetBUByIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetServerBUMapping")]
		public ISingleResult<GetServerBUMappingResult> GetServerBUMapping([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<GetServerBUMappingResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.KnowledgeBase_DeleteFileAttachment")]
		public int KnowledgeBase_DeleteFileAttachment([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RowGuid", DbType="UniqueIdentifier")] System.Nullable<System.Guid> rowGuid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rowGuid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.KnowledgeBase_DeleteKeywordMapping")]
		public int KnowledgeBase_DeleteKeywordMapping([global::System.Data.Linq.Mapping.ParameterAttribute(Name="KnowledgeBaseID", DbType="Int")] System.Nullable<int> knowledgeBaseID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), knowledgeBaseID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.KnowledgeBase_DeleteReferenceLink")]
		public int KnowledgeBase_DeleteReferenceLink([global::System.Data.Linq.Mapping.ParameterAttribute(Name="KnowledgeBaseID", DbType="Int")] System.Nullable<int> knowledgeBaseID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), knowledgeBaseID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.KnowledgeBase_DeleteUnuseFileAttachment")]
		public int KnowledgeBase_DeleteUnuseFileAttachment()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.KnowledgeBase_GetFileAttachment")]
		public ISingleResult<KnowledgeBase_GetFileAttachmentResult> KnowledgeBase_GetFileAttachment([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RowGuid", DbType="UniqueIdentifier")] System.Nullable<System.Guid> rowGuid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rowGuid);
			return ((ISingleResult<KnowledgeBase_GetFileAttachmentResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.KnowledgeBase_GetKMInfo")]
		public ISingleResult<KnowledgeBase_GetKMInfoResult> KnowledgeBase_GetKMInfo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<KnowledgeBase_GetKMInfoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.KnowledgeBase_Insert")]
		public int KnowledgeBase_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Title", DbType="VarChar(100)")] string title, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="VarChar(1000)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Solution", DbType="Text")] string solution, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CreatedBy", DbType="Int")] System.Nullable<int> createdBy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KnowledgeBaseID", DbType="Int")] ref System.Nullable<int> knowledgeBaseID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), title, description, solution, createdBy, knowledgeBaseID);
			knowledgeBaseID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.KnowledgeBase_InsertComment")]
		public int KnowledgeBase_InsertComment([global::System.Data.Linq.Mapping.ParameterAttribute(Name="KnowledgebaseId", DbType="Int")] System.Nullable<int> knowledgebaseId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Message", DbType="VarChar(1000)")] string message, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CreatedBy", DbType="Int")] System.Nullable<int> createdBy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="Int")] System.Nullable<int> status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), knowledgebaseId, message, createdBy, status);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.KnowledgeBase_InsertFileAttachment")]
		public int KnowledgeBase_InsertFileAttachment([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FileName", DbType="VarChar(250)")] string fileName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FileSize", DbType="Int")] System.Nullable<int> fileSize, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KnowledgebaseId", DbType="Int")] System.Nullable<int> knowledgebaseId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Attachment", DbType="VarBinary(MAX)")] System.Data.Linq.Binary attachment, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FileType", DbType="VarChar(50)")] string fileType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Createdby", DbType="Int")] System.Nullable<int> createdby, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="Char(1)")] System.Nullable<char> status, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RowGuid", DbType="UniqueIdentifier")] ref System.Nullable<System.Guid> rowGuid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fileName, fileSize, knowledgebaseId, attachment, fileType, createdby, status, rowGuid);
			rowGuid = ((System.Nullable<System.Guid>)(result.GetParameterValue(7)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.KnowledgeBase_InsertKeywordMapping")]
		public int KnowledgeBase_InsertKeywordMapping([global::System.Data.Linq.Mapping.ParameterAttribute(Name="KnowledgeBaseID", DbType="Int")] System.Nullable<int> knowledgeBaseID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Keyword", DbType="VarChar(1000)")] string keyword)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), knowledgeBaseID, keyword);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.KnowledgeBase_InsertReferenceLink")]
		public int KnowledgeBase_InsertReferenceLink([global::System.Data.Linq.Mapping.ParameterAttribute(Name="KnowledgeBaseID", DbType="Int")] System.Nullable<int> knowledgeBaseID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReferenceValue", DbType="VarChar(50)")] string referenceValue, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReferenceType", DbType="SmallInt")] System.Nullable<short> referenceType)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), knowledgeBaseID, referenceValue, referenceType);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.KnowledgeBase_Search")]
		public ISingleResult<KnowledgeBase_SearchResult> KnowledgeBase_Search([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Keyword", DbType="VarChar(1000)")] string keyword, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pageNum, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pageSize, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VirtualRowsCount", DbType="Int")] ref System.Nullable<int> virtualRowsCount)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), keyword, pageNum, pageSize, virtualRowsCount);
			virtualRowsCount = ((System.Nullable<int>)(result.GetParameterValue(3)));
			return ((ISingleResult<KnowledgeBase_SearchResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.KnowledgeBase_Update")]
		public int KnowledgeBase_Update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Title", DbType="VarChar(100)")] string title, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="VarChar(1000)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Solution", DbType="Text")] string solution, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UpdatedBy", DbType="Int")] System.Nullable<int> updatedBy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KnowledgeBaseID", DbType="Int")] System.Nullable<int> knowledgeBaseID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), title, description, solution, updatedBy, knowledgeBaseID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.KnowledgeBase_UpdateFileAttachment")]
		public int KnowledgeBase_UpdateFileAttachment([global::System.Data.Linq.Mapping.ParameterAttribute(Name="KnowledgebaseId", DbType="Int")] System.Nullable<int> knowledgebaseId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RowGuid", DbType="UniqueIdentifier")] System.Nullable<System.Guid> rowGuid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), knowledgebaseId, rowGuid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.log_DropOldLog")]
		public int log_DropOldLog()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.log_getALLBU")]
		public ISingleResult<log_getALLBUResult> log_getALLBU()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<log_getALLBUResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.log_InsertNewMessage")]
		public int log_InsertNewMessage(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AppDate", DbType="DateTime")] System.Nullable<System.DateTime> appDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Thread", DbType="VarChar(20)")] string thread, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Level", DbType="Char(5)")] string level, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Logger", DbType="VarChar(100)")] string logger, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Message", DbType="NVarChar(MAX)")] string message, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AppName", DbType="VarChar(20)")] string appName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExKey1", DbType="VarChar(20)")] string exKey1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExKey2", DbType="VarChar(20)")] string exKey2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExKey3", DbType="VarChar(20)")] string exKey3, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExKey4", DbType="VarChar(20)")] string exKey4, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExKey5", DbType="VarChar(20)")] string exKey5, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExKey6", DbType="VarChar(20)")] string exKey6, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExKey7", DbType="VarChar(20)")] string exKey7, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExKey8", DbType="VarChar(20)")] string exKey8, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExKey9", DbType="VarChar(20)")] string exKey9, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExKey10", DbType="VarChar(20)")] string exKey10, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Exception", DbType="NVarChar(MAX)")] string exception, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ErrorCode", DbType="Char(10)")] string errorCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Src", DbType="VarChar(20)")] string src)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), appDate, thread, level, logger, message, appName, exKey1, exKey2, exKey3, exKey4, exKey5, exKey6, exKey7, exKey8, exKey9, exKey10, exception, errorCode, src);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.log_LiveMonitoring")]
		public ISingleResult<log_LiveMonitoringResult> log_LiveMonitoring([global::System.Data.Linq.Mapping.ParameterAttribute(Name="APTime", DbType="DateTime")] System.Nullable<System.DateTime> aPTime, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TimeSpanInMins", DbType="SmallInt")] System.Nullable<short> timeSpanInMins, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Level", DbType="Char(5)")] string level, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TimeType", DbType="Int")] System.Nullable<int> timeType)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aPTime, timeSpanInMins, level, timeType);
			return ((ISingleResult<log_LiveMonitoringResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.log_QueryLog")]
		public ISingleResult<log_QueryLogResult> log_QueryLog(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Src", DbType="VarChar(20)")] string src, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AppBeginDate", DbType="DateTime")] System.Nullable<System.DateTime> appBeginDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AppEndDate", DbType="DateTime")] System.Nullable<System.DateTime> appEndDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Thread", DbType="VarChar(20)")] string thread, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Level", DbType="Char(5)")] string level, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Logger", DbType="VarChar(100)")] string logger, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BUID", DbType="SmallInt")] System.Nullable<short> bUID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AppName", DbType="VarChar(20)")] string appName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExKey1", DbType="VarChar(20)")] string exKey1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExKey2", DbType="VarChar(20)")] string exKey2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExKey3", DbType="VarChar(20)")] string exKey3, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExKey4", DbType="VarChar(20)")] string exKey4, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExKey5", DbType="VarChar(20)")] string exKey5, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExKey6", DbType="VarChar(20)")] string exKey6, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExKey7", DbType="VarChar(20)")] string exKey7, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExKey8", DbType="VarChar(20)")] string exKey8, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExKey9", DbType="VarChar(20)")] string exKey9, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExKey10", DbType="VarChar(20)")] string exKey10, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ErrorCode", DbType="Char(10)")] string errorCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Message", DbType="VarChar(100)")] string message, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pageNum, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pageSize, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="VirtualRowsCount", DbType="Int")] ref System.Nullable<int> virtualRowsCount)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), src, appBeginDate, appEndDate, thread, level, logger, bUID, appName, exKey1, exKey2, exKey3, exKey4, exKey5, exKey6, exKey7, exKey8, exKey9, exKey10, errorCode, message, pageNum, pageSize, virtualRowsCount);
			virtualRowsCount = ((System.Nullable<int>)(result.GetParameterValue(22)));
			return ((ISingleResult<log_QueryLogResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.log_QueryLogById")]
		public ISingleResult<log_QueryLogByIdResult> log_QueryLogById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="BigInt")] System.Nullable<long> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<log_QueryLogByIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ServerBUMapping_Delete")]
		public int ServerBUMapping_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ServerBUMapping_Insert")]
		public int ServerBUMapping_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BUID", DbType="SmallInt")] System.Nullable<short> bUID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ServerIP", DbType="VarChar(50)")] string serverIP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ServerName", DbType="VarChar(50)")] string serverName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="SmallInt")] System.Nullable<short> status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), bUID, serverIP, serverName, status);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ServerBUMapping_Search")]
		public ISingleResult<ServerBUMapping_SearchResult> ServerBUMapping_Search([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Keyword", DbType="VarChar(1000)")] string keyword, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BUID", DbType="SmallInt")] System.Nullable<short> bUID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pageNum, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pageSize, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VirtualRowsCount", DbType="Int")] ref System.Nullable<int> virtualRowsCount)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), keyword, bUID, pageNum, pageSize, virtualRowsCount);
			virtualRowsCount = ((System.Nullable<int>)(result.GetParameterValue(4)));
			return ((ISingleResult<ServerBUMapping_SearchResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ServerBUMapping_Update")]
		public int ServerBUMapping_Update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BUID", DbType="SmallInt")] System.Nullable<short> bUID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ServerIP", DbType="VarChar(50)")] string serverIP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ServerName", DbType="VarChar(50)")] string serverName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="SmallInt")] System.Nullable<short> status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, bUID, serverIP, serverName, status);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.state_LogPieTrendByApp")]
		public ISingleResult<state_LogPieTrendByAppResult> state_LogPieTrendByApp([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UseDBTime", DbType="Bit")] System.Nullable<bool> useDBTime, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PastHrs", DbType="TinyInt")] System.Nullable<byte> pastHrs, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BUID", DbType="SmallInt")] System.Nullable<short> bUID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BaseDateTime", DbType="DateTime")] ref System.Nullable<System.DateTime> baseDateTime)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), useDBTime, pastHrs, bUID, baseDateTime);
			baseDateTime = ((System.Nullable<System.DateTime>)(result.GetParameterValue(3)));
			return ((ISingleResult<state_LogPieTrendByAppResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.state_LogPieTrendByBU")]
		public ISingleResult<state_LogPieTrendByBUResult> state_LogPieTrendByBU([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UseDBTime", DbType="Bit")] System.Nullable<bool> useDBTime, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PastHrs", DbType="TinyInt")] System.Nullable<byte> pastHrs, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Level", DbType="Char(5)")] string level, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BaseDateTime", DbType="DateTime")] ref System.Nullable<System.DateTime> baseDateTime)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), useDBTime, pastHrs, level, baseDateTime);
			baseDateTime = ((System.Nullable<System.DateTime>)(result.GetParameterValue(3)));
			return ((ISingleResult<state_LogPieTrendByBUResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.state_LogPieTrendByLevel")]
		public ISingleResult<state_LogPieTrendByLevelResult> state_LogPieTrendByLevel([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UseDBTime", DbType="Bit")] System.Nullable<bool> useDBTime, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PastHrs", DbType="TinyInt")] System.Nullable<byte> pastHrs, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BUID", DbType="SmallInt")] System.Nullable<short> bUID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BaseDateTime", DbType="DateTime")] ref System.Nullable<System.DateTime> baseDateTime)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), useDBTime, pastHrs, bUID, baseDateTime);
			baseDateTime = ((System.Nullable<System.DateTime>)(result.GetParameterValue(3)));
			return ((ISingleResult<state_LogPieTrendByLevelResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.state_LogTrendByBU")]
		public ISingleResult<state_LogTrendByBUResult> state_LogTrendByBU([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UseDBTime", DbType="Bit")] System.Nullable<bool> useDBTime, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PastHrs", DbType="TinyInt")] System.Nullable<byte> pastHrs, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Level", DbType="Char(5)")] string level, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BaseDateTime", DbType="DateTime")] ref System.Nullable<System.DateTime> baseDateTime)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), useDBTime, pastHrs, level, baseDateTime);
			baseDateTime = ((System.Nullable<System.DateTime>)(result.GetParameterValue(3)));
			return ((ISingleResult<state_LogTrendByBUResult>)(result.ReturnValue));
		}
	}
	
	public partial class state_LogTrendByLevelResult
	{
		
		private System.Nullable<int> _OffsetMins;
		
		private string _Level;
		
		private System.Nullable<int> _COUNT;
		
		public state_LogTrendByLevelResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OffsetMins", DbType="Int")]
		public System.Nullable<int> OffsetMins
		{
			get
			{
				return this._OffsetMins;
			}
			set
			{
				if ((this._OffsetMins != value))
				{
					this._OffsetMins = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Level]", Storage="_Level", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string Level
		{
			get
			{
				return this._Level;
			}
			set
			{
				if ((this._Level != value))
				{
					this._Level = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNT", DbType="Int")]
		public System.Nullable<int> COUNT
		{
			get
			{
				return this._COUNT;
			}
			set
			{
				if ((this._COUNT != value))
				{
					this._COUNT = value;
				}
			}
		}
	}
	
	public partial class Account_GetALLUserResult
	{
		
		private short _UserID;
		
		private string _LoginID;
		
		private string _PositionName;
		
		private System.Nullable<short> _BUID;
		
		private string _UserName;
		
		private string _Remark;
		
		private byte _Status;
		
		private byte _UserType;
		
		private System.Data.Linq.Binary _Picture;
		
		private string _PictureType;
		
		private System.DateTime _DateCreated;
		
		private System.Nullable<System.DateTime> _DateUpdated;
		
		public Account_GetALLUserResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="SmallInt NOT NULL")]
		public short UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginID", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string LoginID
		{
			get
			{
				return this._LoginID;
			}
			set
			{
				if ((this._LoginID != value))
				{
					this._LoginID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PositionName", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string PositionName
		{
			get
			{
				return this._PositionName;
			}
			set
			{
				if ((this._PositionName != value))
				{
					this._PositionName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUID", DbType="SmallInt")]
		public System.Nullable<short> BUID
		{
			get
			{
				return this._BUID;
			}
			set
			{
				if ((this._BUID != value))
				{
					this._BUID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="VarChar(256)")]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this._Remark = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="TinyInt NOT NULL")]
		public byte Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserType", DbType="TinyInt NOT NULL")]
		public byte UserType
		{
			get
			{
				return this._UserType;
			}
			set
			{
				if ((this._UserType != value))
				{
					this._UserType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Picture", DbType="Image")]
		public System.Data.Linq.Binary Picture
		{
			get
			{
				return this._Picture;
			}
			set
			{
				if ((this._Picture != value))
				{
					this._Picture = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PictureType", DbType="VarChar(5)")]
		public string PictureType
		{
			get
			{
				return this._PictureType;
			}
			set
			{
				if ((this._PictureType != value))
				{
					this._PictureType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this._DateCreated = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateUpdated", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateUpdated
		{
			get
			{
				return this._DateUpdated;
			}
			set
			{
				if ((this._DateUpdated != value))
				{
					this._DateUpdated = value;
				}
			}
		}
	}
	
	public partial class Account_SearchResult
	{
		
		private System.Nullable<long> _ROW_NO;
		
		private short _UserID;
		
		private string _LoginID;
		
		private string _PositionName;
		
		private int _PositionID;
		
		private System.Nullable<short> _BUID;
		
		private string _BUName;
		
		private string _UserName;
		
		private string _EMail;
		
		private string _Remark;
		
		private byte _Status;
		
		private byte _UserType;
		
		private System.Data.Linq.Binary _Picture;
		
		private string _PictureType;
		
		private System.DateTime _DateCreated;
		
		private System.Nullable<System.DateTime> _DateUpdated;
		
		public Account_SearchResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROW_NO", DbType="BigInt")]
		public System.Nullable<long> ROW_NO
		{
			get
			{
				return this._ROW_NO;
			}
			set
			{
				if ((this._ROW_NO != value))
				{
					this._ROW_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="SmallInt NOT NULL")]
		public short UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginID", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string LoginID
		{
			get
			{
				return this._LoginID;
			}
			set
			{
				if ((this._LoginID != value))
				{
					this._LoginID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PositionName", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string PositionName
		{
			get
			{
				return this._PositionName;
			}
			set
			{
				if ((this._PositionName != value))
				{
					this._PositionName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PositionID", DbType="Int NOT NULL")]
		public int PositionID
		{
			get
			{
				return this._PositionID;
			}
			set
			{
				if ((this._PositionID != value))
				{
					this._PositionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUID", DbType="SmallInt")]
		public System.Nullable<short> BUID
		{
			get
			{
				return this._BUID;
			}
			set
			{
				if ((this._BUID != value))
				{
					this._BUID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUName", DbType="VarChar(50)")]
		public string BUName
		{
			get
			{
				return this._BUName;
			}
			set
			{
				if ((this._BUName != value))
				{
					this._BUName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMail", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string EMail
		{
			get
			{
				return this._EMail;
			}
			set
			{
				if ((this._EMail != value))
				{
					this._EMail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="VarChar(256)")]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this._Remark = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="TinyInt NOT NULL")]
		public byte Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserType", DbType="TinyInt NOT NULL")]
		public byte UserType
		{
			get
			{
				return this._UserType;
			}
			set
			{
				if ((this._UserType != value))
				{
					this._UserType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Picture", DbType="Image")]
		public System.Data.Linq.Binary Picture
		{
			get
			{
				return this._Picture;
			}
			set
			{
				if ((this._Picture != value))
				{
					this._Picture = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PictureType", DbType="VarChar(5)")]
		public string PictureType
		{
			get
			{
				return this._PictureType;
			}
			set
			{
				if ((this._PictureType != value))
				{
					this._PictureType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this._DateCreated = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateUpdated", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateUpdated
		{
			get
			{
				return this._DateUpdated;
			}
			set
			{
				if ((this._DateUpdated != value))
				{
					this._DateUpdated = value;
				}
			}
		}
	}
	
	public partial class Account_SearchByUserIDResult
	{
		
		private short _UserID;
		
		private string _LoginID;
		
		private string _Password;
		
		private System.Nullable<int> _PositionID;
		
		private System.Nullable<short> _BUID;
		
		private string _UserName;
		
		private string _Email;
		
		private string _Remark;
		
		private byte _Status;
		
		private byte _UserType;
		
		private System.Data.Linq.Binary _Picture;
		
		private string _PictureType;
		
		private System.DateTime _DateCreated;
		
		private System.Nullable<System.DateTime> _DateUpdated;
		
		public Account_SearchByUserIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="SmallInt NOT NULL")]
		public short UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginID", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string LoginID
		{
			get
			{
				return this._LoginID;
			}
			set
			{
				if ((this._LoginID != value))
				{
					this._LoginID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PositionID", DbType="Int")]
		public System.Nullable<int> PositionID
		{
			get
			{
				return this._PositionID;
			}
			set
			{
				if ((this._PositionID != value))
				{
					this._PositionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUID", DbType="SmallInt")]
		public System.Nullable<short> BUID
		{
			get
			{
				return this._BUID;
			}
			set
			{
				if ((this._BUID != value))
				{
					this._BUID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="VarChar(256)")]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this._Remark = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="TinyInt NOT NULL")]
		public byte Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserType", DbType="TinyInt NOT NULL")]
		public byte UserType
		{
			get
			{
				return this._UserType;
			}
			set
			{
				if ((this._UserType != value))
				{
					this._UserType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Picture", DbType="Image")]
		public System.Data.Linq.Binary Picture
		{
			get
			{
				return this._Picture;
			}
			set
			{
				if ((this._Picture != value))
				{
					this._Picture = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PictureType", DbType="VarChar(5)")]
		public string PictureType
		{
			get
			{
				return this._PictureType;
			}
			set
			{
				if ((this._PictureType != value))
				{
					this._PictureType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this._DateCreated = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateUpdated", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateUpdated
		{
			get
			{
				return this._DateUpdated;
			}
			set
			{
				if ((this._DateUpdated != value))
				{
					this._DateUpdated = value;
				}
			}
		}
	}
	
	public partial class GetAllBUResult
	{
		
		private short _BUID;
		
		private string _BUName;
		
		public GetAllBUResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUID", DbType="SmallInt NOT NULL")]
		public short BUID
		{
			get
			{
				return this._BUID;
			}
			set
			{
				if ((this._BUID != value))
				{
					this._BUID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string BUName
		{
			get
			{
				return this._BUName;
			}
			set
			{
				if ((this._BUName != value))
				{
					this._BUName = value;
				}
			}
		}
	}
	
	public partial class GetAllPositionResult
	{
		
		private int _PositionID;
		
		private System.Nullable<short> _BUID;
		
		private string _PositionName;
		
		private System.Nullable<byte> _AccessType;
		
		private byte _Status;
		
		private System.DateTime _DateCreated;
		
		private System.Nullable<System.DateTime> _DateUpdated;
		
		private short _CreatedBy;
		
		private System.Nullable<short> _UpdatedBy;
		
		public GetAllPositionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PositionID", DbType="Int NOT NULL")]
		public int PositionID
		{
			get
			{
				return this._PositionID;
			}
			set
			{
				if ((this._PositionID != value))
				{
					this._PositionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUID", DbType="SmallInt")]
		public System.Nullable<short> BUID
		{
			get
			{
				return this._BUID;
			}
			set
			{
				if ((this._BUID != value))
				{
					this._BUID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PositionName", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string PositionName
		{
			get
			{
				return this._PositionName;
			}
			set
			{
				if ((this._PositionName != value))
				{
					this._PositionName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccessType", DbType="TinyInt")]
		public System.Nullable<byte> AccessType
		{
			get
			{
				return this._AccessType;
			}
			set
			{
				if ((this._AccessType != value))
				{
					this._AccessType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="TinyInt NOT NULL")]
		public byte Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this._DateCreated = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateUpdated", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateUpdated
		{
			get
			{
				return this._DateUpdated;
			}
			set
			{
				if ((this._DateUpdated != value))
				{
					this._DateUpdated = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="SmallInt NOT NULL")]
		public short CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this._CreatedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy", DbType="SmallInt")]
		public System.Nullable<short> UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this._UpdatedBy = value;
				}
			}
		}
	}
	
	public partial class GetBUByIDResult
	{
		
		private short _BUID;
		
		private string _BUName;
		
		public GetBUByIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUID", DbType="SmallInt NOT NULL")]
		public short BUID
		{
			get
			{
				return this._BUID;
			}
			set
			{
				if ((this._BUID != value))
				{
					this._BUID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string BUName
		{
			get
			{
				return this._BUName;
			}
			set
			{
				if ((this._BUName != value))
				{
					this._BUName = value;
				}
			}
		}
	}
	
	public partial class GetServerBUMappingResult
	{
		
		private int _ID;
		
		private short _BUID;
		
		private string _BUName;
		
		private string _ServerIP;
		
		private string _ServerName;
		
		private System.Nullable<short> _Status;
		
		public GetServerBUMappingResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUID", DbType="SmallInt NOT NULL")]
		public short BUID
		{
			get
			{
				return this._BUID;
			}
			set
			{
				if ((this._BUID != value))
				{
					this._BUID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string BUName
		{
			get
			{
				return this._BUName;
			}
			set
			{
				if ((this._BUName != value))
				{
					this._BUName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServerIP", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ServerIP
		{
			get
			{
				return this._ServerIP;
			}
			set
			{
				if ((this._ServerIP != value))
				{
					this._ServerIP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServerName", DbType="VarChar(50)")]
		public string ServerName
		{
			get
			{
				return this._ServerName;
			}
			set
			{
				if ((this._ServerName != value))
				{
					this._ServerName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="SmallInt")]
		public System.Nullable<short> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
	}
	
	public partial class KnowledgeBase_GetFileAttachmentResult
	{
		
		private System.Guid _RowGuid;
		
		private int _FileID;
		
		private string _FileName;
		
		private int _FileSize;
		
		private System.Nullable<int> _KnowledgebaseId;
		
		private System.Data.Linq.Binary _Attachment;
		
		private string _FileType;
		
		private System.Nullable<short> _Createdby;
		
		private System.Nullable<System.DateTime> _DateCreated;
		
		private System.Nullable<char> _Status;
		
		public KnowledgeBase_GetFileAttachmentResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowGuid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid RowGuid
		{
			get
			{
				return this._RowGuid;
			}
			set
			{
				if ((this._RowGuid != value))
				{
					this._RowGuid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileID", DbType="Int NOT NULL")]
		public int FileID
		{
			get
			{
				return this._FileID;
			}
			set
			{
				if ((this._FileID != value))
				{
					this._FileID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this._FileName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileSize", DbType="Int NOT NULL")]
		public int FileSize
		{
			get
			{
				return this._FileSize;
			}
			set
			{
				if ((this._FileSize != value))
				{
					this._FileSize = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KnowledgebaseId", DbType="Int")]
		public System.Nullable<int> KnowledgebaseId
		{
			get
			{
				return this._KnowledgebaseId;
			}
			set
			{
				if ((this._KnowledgebaseId != value))
				{
					this._KnowledgebaseId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Attachment", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false)]
		public System.Data.Linq.Binary Attachment
		{
			get
			{
				return this._Attachment;
			}
			set
			{
				if ((this._Attachment != value))
				{
					this._Attachment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileType", DbType="NVarChar(50)")]
		public string FileType
		{
			get
			{
				return this._FileType;
			}
			set
			{
				if ((this._FileType != value))
				{
					this._FileType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Createdby", DbType="SmallInt")]
		public System.Nullable<short> Createdby
		{
			get
			{
				return this._Createdby;
			}
			set
			{
				if ((this._Createdby != value))
				{
					this._Createdby = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this._DateCreated = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Char(1)")]
		public System.Nullable<char> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
	}
	
	public partial class KnowledgeBase_GetKMInfoResult
	{
		
		private int _KnowledgebaseID;
		
		private string _Title;
		
		private string _Solution;
		
		private string _Description;
		
		private int _Recommend;
		
		private string _UserName;
		
		private System.DateTime _DateCreated;
		
		private string _UpdatedBy;
		
		private System.Nullable<System.DateTime> _DateUpdated;
		
		public KnowledgeBase_GetKMInfoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KnowledgebaseID", DbType="Int NOT NULL")]
		public int KnowledgebaseID
		{
			get
			{
				return this._KnowledgebaseID;
			}
			set
			{
				if ((this._KnowledgebaseID != value))
				{
					this._KnowledgebaseID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Solution", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Solution
		{
			get
			{
				return this._Solution;
			}
			set
			{
				if ((this._Solution != value))
				{
					this._Solution = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Recommend", DbType="Int NOT NULL")]
		public int Recommend
		{
			get
			{
				return this._Recommend;
			}
			set
			{
				if ((this._Recommend != value))
				{
					this._Recommend = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this._DateCreated = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy", DbType="VarChar(50)")]
		public string UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this._UpdatedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateUpdated", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateUpdated
		{
			get
			{
				return this._DateUpdated;
			}
			set
			{
				if ((this._DateUpdated != value))
				{
					this._DateUpdated = value;
				}
			}
		}
	}
	
	public partial class KnowledgeBase_SearchResult
	{
		
		private System.Nullable<long> _ROW_NO;
		
		private int _KnowledgebaseID;
		
		private string _Title;
		
		private string _Description;
		
		private string _Solution;
		
		private short _CreatedBy;
		
		private System.DateTime _DateCreated;
		
		private System.Nullable<short> _UpdatedBy;
		
		private System.Nullable<System.DateTime> _DateUpdated;
		
		private int _Recommend;
		
		private System.Nullable<int> _Comments;
		
		public KnowledgeBase_SearchResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROW_NO", DbType="BigInt")]
		public System.Nullable<long> ROW_NO
		{
			get
			{
				return this._ROW_NO;
			}
			set
			{
				if ((this._ROW_NO != value))
				{
					this._ROW_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KnowledgebaseID", DbType="Int NOT NULL")]
		public int KnowledgebaseID
		{
			get
			{
				return this._KnowledgebaseID;
			}
			set
			{
				if ((this._KnowledgebaseID != value))
				{
					this._KnowledgebaseID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Solution", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Solution
		{
			get
			{
				return this._Solution;
			}
			set
			{
				if ((this._Solution != value))
				{
					this._Solution = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="SmallInt NOT NULL")]
		public short CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this._CreatedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this._DateCreated = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy", DbType="SmallInt")]
		public System.Nullable<short> UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this._UpdatedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateUpdated", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateUpdated
		{
			get
			{
				return this._DateUpdated;
			}
			set
			{
				if ((this._DateUpdated != value))
				{
					this._DateUpdated = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Recommend", DbType="Int NOT NULL")]
		public int Recommend
		{
			get
			{
				return this._Recommend;
			}
			set
			{
				if ((this._Recommend != value))
				{
					this._Recommend = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comments", DbType="Int")]
		public System.Nullable<int> Comments
		{
			get
			{
				return this._Comments;
			}
			set
			{
				if ((this._Comments != value))
				{
					this._Comments = value;
				}
			}
		}
	}
	
	public partial class log_getALLBUResult
	{
		
		private short _BUID;
		
		private string _BUName;
		
		public log_getALLBUResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUID", DbType="SmallInt NOT NULL")]
		public short BUID
		{
			get
			{
				return this._BUID;
			}
			set
			{
				if ((this._BUID != value))
				{
					this._BUID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string BUName
		{
			get
			{
				return this._BUName;
			}
			set
			{
				if ((this._BUName != value))
				{
					this._BUName = value;
				}
			}
		}
	}
	
	public partial class log_LiveMonitoringResult
	{
		
		private string _Level;
		
		private System.Nullable<short> _BUID;
		
		private string _BUName;
		
		private string _AppName;
		
		private System.Nullable<System.DateTime> _DBTime;
		
		private System.Nullable<System.DateTime> _DBPastTime;
		
		private System.Nullable<int> _COUNT;
		
		public log_LiveMonitoringResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Level]", Storage="_Level", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string Level
		{
			get
			{
				return this._Level;
			}
			set
			{
				if ((this._Level != value))
				{
					this._Level = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUID", DbType="SmallInt")]
		public System.Nullable<short> BUID
		{
			get
			{
				return this._BUID;
			}
			set
			{
				if ((this._BUID != value))
				{
					this._BUID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUName", DbType="VarChar(50)")]
		public string BUName
		{
			get
			{
				return this._BUName;
			}
			set
			{
				if ((this._BUName != value))
				{
					this._BUName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppName", DbType="VarChar(20)")]
		public string AppName
		{
			get
			{
				return this._AppName;
			}
			set
			{
				if ((this._AppName != value))
				{
					this._AppName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DBTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> DBTime
		{
			get
			{
				return this._DBTime;
			}
			set
			{
				if ((this._DBTime != value))
				{
					this._DBTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DBPastTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> DBPastTime
		{
			get
			{
				return this._DBPastTime;
			}
			set
			{
				if ((this._DBPastTime != value))
				{
					this._DBPastTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNT", DbType="Int")]
		public System.Nullable<int> COUNT
		{
			get
			{
				return this._COUNT;
			}
			set
			{
				if ((this._COUNT != value))
				{
					this._COUNT = value;
				}
			}
		}
	}
	
	public partial class log_QueryLogResult
	{
		
		private System.Nullable<long> _ROW_NO;
		
		private long _ID;
		
		private System.DateTime _AppLoggingDT;
		
		private string _Thread;
		
		private string _Level;
		
		private string _Logger;
		
		private string _Message;
		
		private System.DateTime _DBLoggingDT;
		
		private short _BUID;
		
		private string _AppName;
		
		private string _ExKey1;
		
		private string _ExKey2;
		
		private string _ExKey3;
		
		private string _ExKey4;
		
		private string _ExKey5;
		
		private string _ExKey6;
		
		private string _ExKey7;
		
		private string _ExKey8;
		
		private string _ExKey9;
		
		private string _ExKey10;
		
		private string _Src;
		
		private string _Exception;
		
		private string _ErrorCode;
		
		private string _BUName;
		
		public log_QueryLogResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROW_NO", DbType="BigInt")]
		public System.Nullable<long> ROW_NO
		{
			get
			{
				return this._ROW_NO;
			}
			set
			{
				if ((this._ROW_NO != value))
				{
					this._ROW_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="BigInt NOT NULL")]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppLoggingDT", DbType="DateTime NOT NULL")]
		public System.DateTime AppLoggingDT
		{
			get
			{
				return this._AppLoggingDT;
			}
			set
			{
				if ((this._AppLoggingDT != value))
				{
					this._AppLoggingDT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thread", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Thread
		{
			get
			{
				return this._Thread;
			}
			set
			{
				if ((this._Thread != value))
				{
					this._Thread = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Level]", Storage="_Level", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string Level
		{
			get
			{
				return this._Level;
			}
			set
			{
				if ((this._Level != value))
				{
					this._Level = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Logger", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Logger
		{
			get
			{
				return this._Logger;
			}
			set
			{
				if ((this._Logger != value))
				{
					this._Logger = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this._Message = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DBLoggingDT", DbType="DateTime NOT NULL")]
		public System.DateTime DBLoggingDT
		{
			get
			{
				return this._DBLoggingDT;
			}
			set
			{
				if ((this._DBLoggingDT != value))
				{
					this._DBLoggingDT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUID", DbType="SmallInt NOT NULL")]
		public short BUID
		{
			get
			{
				return this._BUID;
			}
			set
			{
				if ((this._BUID != value))
				{
					this._BUID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppName", DbType="VarChar(20)")]
		public string AppName
		{
			get
			{
				return this._AppName;
			}
			set
			{
				if ((this._AppName != value))
				{
					this._AppName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExKey1", DbType="VarChar(20)")]
		public string ExKey1
		{
			get
			{
				return this._ExKey1;
			}
			set
			{
				if ((this._ExKey1 != value))
				{
					this._ExKey1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExKey2", DbType="VarChar(20)")]
		public string ExKey2
		{
			get
			{
				return this._ExKey2;
			}
			set
			{
				if ((this._ExKey2 != value))
				{
					this._ExKey2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExKey3", DbType="VarChar(20)")]
		public string ExKey3
		{
			get
			{
				return this._ExKey3;
			}
			set
			{
				if ((this._ExKey3 != value))
				{
					this._ExKey3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExKey4", DbType="VarChar(20)")]
		public string ExKey4
		{
			get
			{
				return this._ExKey4;
			}
			set
			{
				if ((this._ExKey4 != value))
				{
					this._ExKey4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExKey5", DbType="VarChar(20)")]
		public string ExKey5
		{
			get
			{
				return this._ExKey5;
			}
			set
			{
				if ((this._ExKey5 != value))
				{
					this._ExKey5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExKey6", DbType="VarChar(20)")]
		public string ExKey6
		{
			get
			{
				return this._ExKey6;
			}
			set
			{
				if ((this._ExKey6 != value))
				{
					this._ExKey6 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExKey7", DbType="VarChar(20)")]
		public string ExKey7
		{
			get
			{
				return this._ExKey7;
			}
			set
			{
				if ((this._ExKey7 != value))
				{
					this._ExKey7 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExKey8", DbType="VarChar(20)")]
		public string ExKey8
		{
			get
			{
				return this._ExKey8;
			}
			set
			{
				if ((this._ExKey8 != value))
				{
					this._ExKey8 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExKey9", DbType="VarChar(20)")]
		public string ExKey9
		{
			get
			{
				return this._ExKey9;
			}
			set
			{
				if ((this._ExKey9 != value))
				{
					this._ExKey9 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExKey10", DbType="VarChar(20)")]
		public string ExKey10
		{
			get
			{
				return this._ExKey10;
			}
			set
			{
				if ((this._ExKey10 != value))
				{
					this._ExKey10 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Src", DbType="VarChar(20)")]
		public string Src
		{
			get
			{
				return this._Src;
			}
			set
			{
				if ((this._Src != value))
				{
					this._Src = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Exception", DbType="NVarChar(MAX)")]
		public string Exception
		{
			get
			{
				return this._Exception;
			}
			set
			{
				if ((this._Exception != value))
				{
					this._Exception = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorCode", DbType="VarChar(20)")]
		public string ErrorCode
		{
			get
			{
				return this._ErrorCode;
			}
			set
			{
				if ((this._ErrorCode != value))
				{
					this._ErrorCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUName", DbType="VarChar(50)")]
		public string BUName
		{
			get
			{
				return this._BUName;
			}
			set
			{
				if ((this._BUName != value))
				{
					this._BUName = value;
				}
			}
		}
	}
	
	public partial class log_QueryLogByIdResult
	{
		
		private long _ID;
		
		private System.DateTime _AppLoggingDT;
		
		private string _Thread;
		
		private string _Level;
		
		private string _Logger;
		
		private string _Message;
		
		private System.DateTime _DBLoggingDT;
		
		private short _BUID;
		
		private string _BUName;
		
		private string _AppName;
		
		private string _ExKey1;
		
		private string _ExKey2;
		
		private string _ExKey3;
		
		private string _ExKey4;
		
		private string _ExKey5;
		
		private string _ExKey6;
		
		private string _ExKey7;
		
		private string _ExKey8;
		
		private string _ExKey9;
		
		private string _ExKey10;
		
		private string _Src;
		
		private string _Exception;
		
		private string _ErrorCode;
		
		public log_QueryLogByIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="BigInt NOT NULL")]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppLoggingDT", DbType="DateTime NOT NULL")]
		public System.DateTime AppLoggingDT
		{
			get
			{
				return this._AppLoggingDT;
			}
			set
			{
				if ((this._AppLoggingDT != value))
				{
					this._AppLoggingDT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thread", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Thread
		{
			get
			{
				return this._Thread;
			}
			set
			{
				if ((this._Thread != value))
				{
					this._Thread = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Level]", Storage="_Level", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string Level
		{
			get
			{
				return this._Level;
			}
			set
			{
				if ((this._Level != value))
				{
					this._Level = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Logger", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Logger
		{
			get
			{
				return this._Logger;
			}
			set
			{
				if ((this._Logger != value))
				{
					this._Logger = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this._Message = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DBLoggingDT", DbType="DateTime NOT NULL")]
		public System.DateTime DBLoggingDT
		{
			get
			{
				return this._DBLoggingDT;
			}
			set
			{
				if ((this._DBLoggingDT != value))
				{
					this._DBLoggingDT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUID", DbType="SmallInt NOT NULL")]
		public short BUID
		{
			get
			{
				return this._BUID;
			}
			set
			{
				if ((this._BUID != value))
				{
					this._BUID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUName", DbType="VarChar(50)")]
		public string BUName
		{
			get
			{
				return this._BUName;
			}
			set
			{
				if ((this._BUName != value))
				{
					this._BUName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppName", DbType="VarChar(20)")]
		public string AppName
		{
			get
			{
				return this._AppName;
			}
			set
			{
				if ((this._AppName != value))
				{
					this._AppName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExKey1", DbType="VarChar(20)")]
		public string ExKey1
		{
			get
			{
				return this._ExKey1;
			}
			set
			{
				if ((this._ExKey1 != value))
				{
					this._ExKey1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExKey2", DbType="VarChar(20)")]
		public string ExKey2
		{
			get
			{
				return this._ExKey2;
			}
			set
			{
				if ((this._ExKey2 != value))
				{
					this._ExKey2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExKey3", DbType="VarChar(20)")]
		public string ExKey3
		{
			get
			{
				return this._ExKey3;
			}
			set
			{
				if ((this._ExKey3 != value))
				{
					this._ExKey3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExKey4", DbType="VarChar(20)")]
		public string ExKey4
		{
			get
			{
				return this._ExKey4;
			}
			set
			{
				if ((this._ExKey4 != value))
				{
					this._ExKey4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExKey5", DbType="VarChar(20)")]
		public string ExKey5
		{
			get
			{
				return this._ExKey5;
			}
			set
			{
				if ((this._ExKey5 != value))
				{
					this._ExKey5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExKey6", DbType="VarChar(20)")]
		public string ExKey6
		{
			get
			{
				return this._ExKey6;
			}
			set
			{
				if ((this._ExKey6 != value))
				{
					this._ExKey6 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExKey7", DbType="VarChar(20)")]
		public string ExKey7
		{
			get
			{
				return this._ExKey7;
			}
			set
			{
				if ((this._ExKey7 != value))
				{
					this._ExKey7 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExKey8", DbType="VarChar(20)")]
		public string ExKey8
		{
			get
			{
				return this._ExKey8;
			}
			set
			{
				if ((this._ExKey8 != value))
				{
					this._ExKey8 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExKey9", DbType="VarChar(20)")]
		public string ExKey9
		{
			get
			{
				return this._ExKey9;
			}
			set
			{
				if ((this._ExKey9 != value))
				{
					this._ExKey9 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExKey10", DbType="VarChar(20)")]
		public string ExKey10
		{
			get
			{
				return this._ExKey10;
			}
			set
			{
				if ((this._ExKey10 != value))
				{
					this._ExKey10 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Src", DbType="VarChar(20)")]
		public string Src
		{
			get
			{
				return this._Src;
			}
			set
			{
				if ((this._Src != value))
				{
					this._Src = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Exception", DbType="NVarChar(MAX)")]
		public string Exception
		{
			get
			{
				return this._Exception;
			}
			set
			{
				if ((this._Exception != value))
				{
					this._Exception = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorCode", DbType="VarChar(20)")]
		public string ErrorCode
		{
			get
			{
				return this._ErrorCode;
			}
			set
			{
				if ((this._ErrorCode != value))
				{
					this._ErrorCode = value;
				}
			}
		}
	}
	
	public partial class ServerBUMapping_SearchResult
	{
		
		private System.Nullable<long> _ROW_NO;
		
		private int _ID;
		
		private short _BUID;
		
		private string _BUNAME;
		
		private string _ServerIP;
		
		private string _ServerName;
		
		private System.Nullable<short> _Status;
		
		public ServerBUMapping_SearchResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROW_NO", DbType="BigInt")]
		public System.Nullable<long> ROW_NO
		{
			get
			{
				return this._ROW_NO;
			}
			set
			{
				if ((this._ROW_NO != value))
				{
					this._ROW_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUID", DbType="SmallInt NOT NULL")]
		public short BUID
		{
			get
			{
				return this._BUID;
			}
			set
			{
				if ((this._BUID != value))
				{
					this._BUID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUNAME", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string BUNAME
		{
			get
			{
				return this._BUNAME;
			}
			set
			{
				if ((this._BUNAME != value))
				{
					this._BUNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServerIP", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ServerIP
		{
			get
			{
				return this._ServerIP;
			}
			set
			{
				if ((this._ServerIP != value))
				{
					this._ServerIP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServerName", DbType="VarChar(50)")]
		public string ServerName
		{
			get
			{
				return this._ServerName;
			}
			set
			{
				if ((this._ServerName != value))
				{
					this._ServerName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="SmallInt")]
		public System.Nullable<short> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
	}
	
	public partial class state_LogPieTrendByAppResult
	{
		
		private string _AppName;
		
		private System.Nullable<int> _COUNT;
		
		public state_LogPieTrendByAppResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppName", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string AppName
		{
			get
			{
				return this._AppName;
			}
			set
			{
				if ((this._AppName != value))
				{
					this._AppName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNT", DbType="Int")]
		public System.Nullable<int> COUNT
		{
			get
			{
				return this._COUNT;
			}
			set
			{
				if ((this._COUNT != value))
				{
					this._COUNT = value;
				}
			}
		}
	}
	
	public partial class state_LogPieTrendByBUResult
	{
		
		private string _BU;
		
		private System.Nullable<int> _COUNT;
		
		public state_LogPieTrendByBUResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BU", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string BU
		{
			get
			{
				return this._BU;
			}
			set
			{
				if ((this._BU != value))
				{
					this._BU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNT", DbType="Int")]
		public System.Nullable<int> COUNT
		{
			get
			{
				return this._COUNT;
			}
			set
			{
				if ((this._COUNT != value))
				{
					this._COUNT = value;
				}
			}
		}
	}
	
	public partial class state_LogPieTrendByLevelResult
	{
		
		private string _Level;
		
		private System.Nullable<int> _COUNT;
		
		public state_LogPieTrendByLevelResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Level]", Storage="_Level", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string Level
		{
			get
			{
				return this._Level;
			}
			set
			{
				if ((this._Level != value))
				{
					this._Level = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNT", DbType="Int")]
		public System.Nullable<int> COUNT
		{
			get
			{
				return this._COUNT;
			}
			set
			{
				if ((this._COUNT != value))
				{
					this._COUNT = value;
				}
			}
		}
	}
	
	public partial class state_LogTrendByBUResult
	{
		
		private System.Nullable<int> _OffsetMins;
		
		private string _BU;
		
		private System.Nullable<int> _COUNT;
		
		public state_LogTrendByBUResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OffsetMins", DbType="Int")]
		public System.Nullable<int> OffsetMins
		{
			get
			{
				return this._OffsetMins;
			}
			set
			{
				if ((this._OffsetMins != value))
				{
					this._OffsetMins = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BU", DbType="VarChar(50)")]
		public string BU
		{
			get
			{
				return this._BU;
			}
			set
			{
				if ((this._BU != value))
				{
					this._BU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNT", DbType="Int")]
		public System.Nullable<int> COUNT
		{
			get
			{
				return this._COUNT;
			}
			set
			{
				if ((this._COUNT != value))
				{
					this._COUNT = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
